const $ = s => document.querySelector(s);
const money = n => n.toLocaleString('pt-BR', {style:'currency',currency:'BRL'});
const esc = s => String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const categories = ['Todos','Tênis','Calças','Camisetas','Jaquetas','Acessórios','Promoções'];
let currentFilter='Todos', currentQuery='', currentProduct=null;
const productById = id => PRODUCTS.find(p=>p.id===id);
const matches = (p,filter) => filter==='Todos'||(filter==='Promoções'&&p.oldPrice>p.price)||p.category===filter||p.group===filter;
const normalize = text => text.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
function whatsapp(p,size=''){if(!STORE_CONFIG.whatsapp)return '#contato-demonstracao';const message=`Olá, RUA 011! Vi esta peça na vitrine demonstrativa e gostaria de consultar um modelo igual ou semelhante:\n\n${p.name}${size?'\nTamanho desejado: '+size:''}\nCódigo da peça: ${p.id}\n\nVocês têm disponível? Qual o valor?`;return 'https://wa.me/'+STORE_CONFIG.whatsapp+'?text='+encodeURIComponent(message);}
function card(p){return `<article class="product-card"><button class="product-photo" data-product="${p.id}" aria-label="Ver ${esc(p.name)}"><img src="${p.image}" alt="${esc(p.name)}" loading="lazy" width="480" height="640"></button><div class="product-info"><button class="product-name" data-product="${p.id}">${esc(p.name)}</button><div class="discount">${p.oldPrice>p.price?`-${Math.round((1-p.price/p.oldPrice)*100)}% OFF`:''}</div><div class="prices"><strong>${money(p.price)}</strong>${p.oldPrice>p.price?`<del>${money(p.oldPrice)}</del>`:''}</div><p class="price-caption">Preço de referência · Estoque a confirmar</p><a class="product-whatsapp" href="${whatsapp(p)}" target="_blank" rel="noopener" aria-label="Consultar ${esc(p.name)} no WhatsApp">CHAMAR NO WHATSAPP ↗</a></div></article>`;}
const shelves=[['Calças em destaque','Calças'],['Camisetas e jaquetas','Roupas'],['Tênis · Wave Prophecy','Wave Prophecy'],['Dunk Low & Jordan Low','Nike'],['Promoções','Promoções'],['Acessórios','Acessórios']];
$('#shelves').innerHTML=shelves.map(([title,filter],i)=>{const list=PRODUCTS.filter(p=>filter==='Roupas'?['Camisetas','Jaquetas'].includes(p.category):filter==='Nike'?['Dunk Low','Jordan Low'].includes(p.group):matches(p,filter));return `<section class="shelf"><div class="shelf-head"><h2>${title}</h2><div class="shelf-controls"><button class="see-all" data-filter="${filter}">Ver tudo (${list.length})</button><button data-scroll="shelf-${i}" data-direction="-1" aria-label="Produtos anteriores: ${title}">‹</button><button data-scroll="shelf-${i}" data-direction="1" aria-label="Próximos produtos: ${title}">›</button></div></div><div class="product-track" id="shelf-${i}">${list.map(card).join('')}</div></section>`;}).join('');
$('#banner-shirts').src=PRODUCTS.find(p=>p.category==='Camisetas').image;
$('#banner-pants').src=PRODUCTS.find(p=>p.category==='Calças').image;
$('#banner-shoes').src=PRODUCTS.find(p=>p.group==='Dunk Low').image;
$('#band-product').src=(PRODUCTS.find(p=>p.category==='Jaquetas')||PRODUCTS[0]).image;
function inCategory(p,filter){return filter==='Roupas'?['Camisetas','Jaquetas'].includes(p.category):filter==='Nike'?['Dunk Low','Jordan Low'].includes(p.group):matches(p,filter);}
function showResults(filter='Todos',query='',scroll=true){currentFilter=filter;currentQuery=query;$('#home').hidden=true;$('#results').hidden=false;$('#search-input').value=query;renderResults();if(scroll)$('#results').scrollIntoView({behavior:window.matchMedia('(max-width:700px), (prefers-reduced-motion: reduce)').matches?'instant':'smooth',block:'start'});}
function renderResults(){let list=PRODUCTS.filter(p=>inCategory(p,currentFilter)&&normalize(p.name).includes(normalize(currentQuery)));const sort=$('#sort').value;if(sort==='price-asc')list.sort((a,b)=>a.price-b.price);if(sort==='price-desc')list.sort((a,b)=>b.price-a.price);if(sort==='name')list.sort((a,b)=>a.name.localeCompare(b.name,'pt-BR'));$('#results-title').textContent=currentQuery?`Resultados para “${currentQuery}”`:currentFilter==='Todos'?'Todos os produtos':currentFilter==='Nike'?'Dunk Low & Jordan Low':currentFilter;$('#breadcrumb-label').textContent=currentQuery?'Busca':currentFilter;$('#result-count').textContent=`${list.length} ${list.length===1?'produto':'produtos'} no catálogo de referência`;$('#results-grid').innerHTML=list.map(card).join('');$('#empty-results').hidden=list.length>0;$('#filter-chips').innerHTML=categories.map(c=>`<button class="${c===currentFilter?'active':''}" aria-pressed="${c===currentFilter}" data-filter="${c}">${c}</button>`).join('');}
function goHome(){currentFilter='Todos';currentQuery='';$('#home').hidden=false;$('#results').hidden=true;$('#search-input').value='';window.scrollTo({top:0,behavior:window.matchMedia('(max-width:700px), (prefers-reduced-motion: reduce)').matches?'instant':'smooth'});}
function openProduct(id){const p=productById(id);if(!p)return;currentProduct=p;$('#product-content').innerHTML=`<div class="product-detail"><img class="detail-image" src="${p.image}" alt="${esc(p.name)}"><div class="detail-info"><small>${esc(p.category.toUpperCase())}</small><h2 id="product-title">${esc(p.name)}</h2><div class="prices"><strong>${money(p.price)}</strong>${p.oldPrice>p.price?`<del>${money(p.oldPrice)}</del>`:''}</div><p class="detail-note">Preço e foto do catálogo de referência.</p><p class="stock-status">Disponibilidade na loja: <strong>a confirmar</strong></p><label for="product-size">Seu tamanho <small>(opcional)</small></label><input id="product-size" type="text" maxlength="35" placeholder="Ex.: M, 40, 42…"><a class="gold-button" id="product-consult" href="${whatsapp(p)}" target="_blank" rel="noopener">CONSULTAR NO WHATSAPP ↗</a><p class="detail-note">A equipe confirma o estoque, os tamanhos e o preço antes da compra.</p></div></div>`;$('#product-size').addEventListener('input',()=>{$('#product-consult').href=whatsapp(p,$('#product-size').value.trim());});$('#product-dialog').showModal();}
document.addEventListener('click',e=>{const b=e.target.closest('button,a');if(!b)return;if(b.getAttribute('href')==='#contato-demonstracao'){e.preventDefault();if($('#product-dialog').open)$('#product-dialog').close();$('#info-dialog').showModal();return;}if(b.dataset.filter){e.preventDefault();showResults(b.dataset.filter);return;}if(b.dataset.product){openProduct(b.dataset.product);return;}if(b.dataset.close){$('#'+b.dataset.close).close();return;}if(b.dataset.scroll){const row=$('#'+b.dataset.scroll);row.scrollBy({left:row.clientWidth*Number(b.dataset.direction),behavior:window.matchMedia('(max-width:700px), (prefers-reduced-motion: reduce)').matches?'instant':'smooth'});return;}if(b.closest('.logo')||b.classList.contains('footer-sign')||b.id==='back-home'){e.preventDefault();goHome();}if(b.id==='about-preview')$('#info-dialog').showModal();});
$('#search').addEventListener('submit',e=>{e.preventDefault();showResults('Todos',$('#search-input').value.trim());});
$('#sort').addEventListener('change',renderResults);
let messageIndex=0;const messages=['RUA 011 MULTIMARCAS — SEU ESTILO COMEÇA AQUI','ROUPAS, TÊNIS E ACESSÓRIOS EM UM SÓ LUGAR','ESCOLHA SUAS PEÇAS E CONSULTE NO WHATSAPP'];
function message(delta){messageIndex=(messageIndex+delta+messages.length)%messages.length;$('#top-message').textContent=messages[messageIndex];}
$('#top-prev').addEventListener('click',()=>message(-1));$('#top-next').addEventListener('click',()=>message(1));
document.querySelectorAll('dialog').forEach(d=>d.addEventListener('click',e=>{if(e.target===d){const r=d.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)d.close();}}));

if(STORE_CONFIG.whatsapp)document.querySelectorAll('a[href="#contato-demonstracao"]').forEach(a=>a.href='https://wa.me/'+STORE_CONFIG.whatsapp);
